services:
  mysql:
    image: mysql:8.0
    container_name: news-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news-app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "${PORT}:${PORT}"
      - "40000:40000"
    tty: true